language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python manage.py migrate
deploy:
  provider: heroku
  api_key:
    secure: DAHpddrD95qVL6NDsCQFhi13nTGXWfY189pi61bsMph4fKX2rRAd+ccoB+XcQQ9bsqER6KU7pIZ8k9+q1E+JPZdEzVHgJ2/1iDaJtqWoMkLRPYv2wOA9NPG/jJhfDjD8dauzf4y7Nv2SU6Z6KfsHw9cZMpW540mZ0HgCZBhWvtiKgG3YKf8SJ3GE9KcovV/6b7o2Abdu6jwUXmMA3sLzyrbpbWOwOGDRLtCd0aC9g6SjFq7j6q1yjgFw+zfU7qPmIKLLfl+qxqEexnqfXn6cDb69VtwMYwCjk8gAwTM9/8WbQ6QlPcN1psIQ19H1XvRmPpOGEhzXlukay3IDjY5rBK3egv8TPiYLYeOtTUF6GP4yW+V+pIAjBi96hqXbD/AOnxe9RYKv0Kc2f3hJ5iAleYGaS+22AayqeyqEKZ4XNKPrZ6dWHiOCdsOZUGcTDXyHjrmzAU+Z2Og3GO/7WzysfXYUGy13geXY7lyaED6vaT8t5w7Ko/kL1W0AislLQPZeYlcVPFJERM5TbypPHqprGBOvyero+DofDoJmsj8esNk1K30IMK6oOxB9OG2sRy9xCcGRqN9x0CqDI50x+ejpunznQzADatkbfSVXdXZCD9GE1ZblZHNpVslBrJAADH6aE1U/qWczzVnqCxTvWhCpyb1SfKmEKtaa67d0fmtOVGM=
  app: cs3240-project-2-25-new
  on:
    repo: uva-cs3240-f20/project-2-25
    branch: travis-heroku