language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- python manage.py migrate
deploy:
  provider: heroku
  api_key:
    secure: YKCJwjwrz39JY1Yr3R7oZgdOOfRiNJVU5lAsPrrLUUGHMDBOb7tvrEdSjKLmROf14z07ZdBI6TobVq5AKiBOB21KPq5oIGHjF5PMm0WriWEB+Tk2wOs+92WHxO8cK2zA4t8lVpe+aQ0LhDexZgD/emyu6Bn3rXOrcjmAGMNAAtDGQGRvzCnR0bUy/LsGae3V7fCsGPwVt7euTwOXDy0S3sKjP7lhLupJ2innAP4PSVKCYthrK7yOmLjOAoPPKDregcTm83LMGZvD5Z/RX41wHiqFlDP8/8szqqP2EsdmU+k7NIdwYEY7wKm8UTwoEbMQ90OSadtsU3AdwbYIwqjePJwYIhZ1k0KUqp0SeT3x0jQwOu6LmUMImkatIvhHNv1quo/s9Cb9+Xo2dv3HL2FZOCwXFJayXN5ZH9GiVaUPOKUJcKm8iijDGKOoJoLVsGEx0vznSKdqmw2Tl9AD0BXe83S1jYKB6wUOI8jkQRQvQLX+RGBRtKeUBEGdCL2/O2+a3DT+fcLnlxhohbeKx+FEWLtD4DTnGzYYZm46eINQZ56iUSOIM6s40WqB4CE4gZq9QM4mXREJt12sXRJj7Rlo9p1iqCo3r0bRB+g5alla9aIqMewUEub8YE5tHS4Yn20+mr6KyAwETnec+sv2owm8r+QyYSDnOGSeksVWAIunAAQ=
  app: cs3240-project-2-25-new
  on:
    repo: uva-cs3240-f20/project-2-25