# Generated by Django 3.1.1 on 2020-10-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201025_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='name_text',
            new_name='name',
        ),
    ]
