# Generated by Django 3.1.3 on 2020-11-11 21:20

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder', '0007_auto_20201105_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'permissions': (('can_delete', 'Can delete event'),), 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='events',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
