# Generated by Django 3.1.2 on 2020-11-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder', '0011_eventcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='event_comment',
            field=models.CharField(max_length=5000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
