# Generated by Django 3.1.2 on 2020-11-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder', '0012_auto_20201116_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='event_comment',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='name',
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='comment_field',
            field=models.CharField(default=3, max_length=500),
            preserve_default=False,
        ),
    ]
