# Generated by Django 3.1.3 on 2020-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder', '0014_eventcomment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcomment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
