# Generated by Django 3.1.3 on 2020-11-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder', '0015_auto_20201117_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_filter',
            field=models.CharField(blank=True, max_length=500, verbose_name='Default Search Filter'),
        ),
    ]
