# Generated by Django 3.1.3 on 2020-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_finder', '0016_profile_default_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(to='meetup_finder.Events'),
        ),
    ]
